version: '3'

services:
  # postgres database service
  postgres-server:
    image: 'postgis/postgis'
    container_name: postgres-server
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
    volumes:
      - ~/backup/postgres:/data/postgres
    networks:
      - postgres-network
  # postgres database admin console
  pgadmin-server:
    image: dpage/pgadmin4
    container_name: pgadmin-server
    ports:
      - 8082:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    depends_on:
      - postgres-server
    volumes:
      - ~/backup/pgadmin/:/var/lib/pgadmin/
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
